### ISSUE TITLE
P1111111111 is valid and shouldn't be

### ISSUE THREAD

**Issue by keenahn** [tolu/ISO8601-duration#13]
```
nesh> const { parse } = require('iso8601-duration')
undefined
nesh> parse('P1111111111')
{ weeks: 0,
  years: 0,
  months: 0,
  days: 0,
  hours: 0,
  minutes: 0,
  seconds: 0 }
```

**Comment by keenahn** [comment]
Same with `PD`

```
nesh> parse('PD')
{ weeks: 0,
  years: 0,
  months: 0,
  days: 0,
  hours: 0,
  minutes: 0,
  seconds: 0 }
```

**Comment by hlerebours** [comment]
I agree that there is a bug here. Or two:
- The current implementation tolerates any input that _contains_ a valid duration.
- "P" is considered valid in itself.

=> Any string containing a "P" is considered a valid ISO duration, which is obviously not true (is "API" a valid duration?).
