### ISSUE TITLE
TypeError when passing invalid string to parse

### ISSUE THREAD

**Issue by GodOfGrandeur** [tolu/ISO8601-duration#15]
## Steps To Reproduce
`parse('abc');`

## The current behavior
Throws error 

```
TypeError: Cannot read property 'slice' of null
at parse (node_modules/iso8601-duration/lib/index.js:35:10)
```

## The expected behavior

Shouldn't throw a type error.

**Comment by tolu** [comment]
Could for instance add check that throws specific error when `durationString` doesn't match anything.

https://github.com/tolu/ISO8601-duration/blob/5cb2238944c95d6fb0ef9acc3dc15ff1edcd3029/src/index.js#L30

**Comment by ssipos90** [comment]
@tolu I was just encountering this. Maybe nullcheck and throw something specific or return a 0 duration.
