### ISSUE TITLE
Need function to construct iso duration string from given object

### ISSUE THREAD

**Issue by jacobg** [tolu/ISO8601-duration#19]
It would be great to have a function that given an object, will create the iso duration string.

For example, an input of:
```javascript
{ hours: 1 }
```
would return:
```javascript
"P0Y0M0DT1H0M0S"
```

**Comment by tolu** [comment]
I can see why that would make sense but I think it's out of scope for this project since this is aimed at consuming and not constructing iso8601 durations.

The reason being that (without much thought):
- given the example, it seems simple to just do that in your own code
- given to construct from 2 dates, codebase would grow and there are certainly lots of corner cases
- this is the first interest expressed in such a feature

**Comment by tolu** [comment]
we'll keep this issue open and see if others chime in 👍 
Thanks for creating it!

**Comment by luwes** [comment]
I'm looking for this function as well. Use case is to create structured data for a video object, needed for the duration of the video. https://schema.org/VideoObject

**Comment by luwes** [comment]
This should be it I think.

```js
export function secondsToISOString(seconds) {
  let Y = Math.floor(seconds / 60 / 60 / 24 / 365);
  let M = Math.floor(seconds / 60 / 60 / 24 / 30.42 % 12);
  let D = Math.floor(seconds / 60 / 60 / 24 % 30.42);
  let h = Math.floor(seconds / 60 / 60 % 24);
  let m = Math.floor(seconds / 60 % 60);
  let s = Math.floor(seconds % 60);

  if (!seconds) {
    return 'P0D';
  }

  return (
    (seconds < 0 ? '-' : '') +
    'P' +
    (Y ? Y + 'Y' : '') +
    (M ? M + 'M' : '') +
    (D ? D + 'D' : '') +
    (h || m || s ? 'T' : '') +
    (h ? h + 'H' : '') +
    (m ? m + 'M' : '') +
    (s ? s + 'S' : '')
  );
}
```

Tests:

```js
import test from 'tape';
import { secondsToISOString } from '../src/utils.js';

test('secondsToISOString', (t) => {
  t.equal(secondsToISOString(0), 'P0D');
  t.equal(secondsToISOString(120), 'PT2M');
  t.equal(secondsToISOString(3601), 'PT1H1S');
  t.equal(secondsToISOString(1), 'PT1S');
  t.equal(secondsToISOString(5410), 'PT1H30M10S');
  t.equal(secondsToISOString(37226652), 'P1Y2M4DT20H44M12S');
  t.equal(secondsToISOString(37313052), 'P1Y2M5DT20H44M12S');
  t.end();
});
```

**Comment by tolu** [comment]
A better solution is to use this then:
https://www.npmjs.com/package/temporal-polyfill

```js
new Temporal.Duration(0, 0, 0, 40); // => P40D
```

I've decided not to add more logic to this project since the Temporal proposal is around the corner (hopefully 🤞 )
