### ISSUE TITLE
Durations with significant millisecond accuracy are parsed incorrectly

### ISSUE THREAD

**Issue by Langtonm** [tolu/ISO8601-duration#2]
Parsing durations with significant millisecond accuracy (which do not appear to strictly follow the ISO8601 spec) returns incorrect results
        
        E.g:-
        Parse 'PT52M59.989333S' incorrectly returns a duration of :-
        {"weeks":0,"years":0,"months":0,"days":0,"hours":0,"minutes":52,"seconds":0}
        
        however Parse 'PT52M59.989S' correctly returns a duration of :-
        {"weeks":0,"years":0,"months":0,"days":0,"hours":0,"minutes":52,"seconds":59.989}
        
        
        Ideally the module should either correctly convert values that do not strictly conform to 
        the ISO8601 spec 
        	const numbers = '\\d+(?:[\\.,]\\d+)?';
        or it should throw an exception when a value with an unexpected/unconvertible format is provided.

**Comment by tolu** [comment]
Thanks for the issue, PR's are very welcome 😄
