### ISSUE TITLE
Pattern matches P or PT without numbers

### ISSUE THREAD

**Issue by felix-gohla** [tolu/ISO8601-duration#21]
Hi there,

thank you very much for providing this library!  
However, I noticed, that the regex pattern also matches expressions like `P` or `PT`.
According to [Wikipedia](https://en.wikipedia.org/wiki/ISO_8601#Durations), this is no valid duration:

> However, at least one element must be present, thus "P" is not a valid representation for a duration of 0 seconds.

<img width="1473" alt="Screenshot 2021-05-22 at 18 57 36" src="https://user-images.githubusercontent.com/37421906/119234720-9ace4b00-bb2f-11eb-93a0-640f21e957ae.png">

**Comment by felix-gohla** [comment]
Any updates here? 😀

**Comment by tolu** [comment]
Sorry for the extremely late reply 🙈 🙏 
This repo has been dead to me for far too long now!

Thanks for taking the time to write the issue, I'm currently working on fixing this and validating what this library does against https://tc39.es/proposal-temporal/docs/duration.html

**Comment by felix-gohla** [comment]
Cool and thanks for your reply. :blush: Also have a look at #22. Not sure if it meets your requirements.
