### ISSUE TITLE
Better TypeScript typing for ISO8601-duration strings

### ISSUE THREAD

**Issue by Mesoptier** [tolu/ISO8601-duration#24]
TypeScript has support for constructing string types using template strings ([Template Literal Types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html)). Those types could be used to construct a string type that allows only valid ISO8601-duration strings instead of any arbitrary string.

For example, something like this may work:

```ts
type Duration =
    | `P${`${number}Y` | ''}${`${number}M` | ''}${`${number}D` | ''}T${`${number}H` | ''}${`${number}M` | ''}${`${number}S` | ''}`
    | `P${number}W`;

// valid assignment
const valid: Duration = 'P1Y2M4DT20H44M12.67S'; 

// invalid assignment: '"test"' is not assignable to type 'Duration'
const invalid: Duration = 'test';
```
[Code example on TS Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAIgrgJwIbAJYHsB2UC8AoKQqAHygAMAFAEgG8zbM4BbAIwgQF8BNMkqAcn4da9Go1bsOAWV6lBwug2ZtOMWQKEAVEUomcAEuvk6xyyTL7HFpvRwDKRoWQJFSlXSo4B1MgG48eAD0gVAAbkgANqgAJlBIAM7xqADmmEwQmMB4AMZY8cBhkTEAXLCIKBjYOAIUAIxcAExSACwwmg0ADPrNzVK1DQB0AGwA7Hb8vlABwVComOFRsQlJqemZpfwARMAQ+Zv8s-FQmOgFyymYSCwR0MDoUKCQAvDIaFj8OXkFcwslZa+VXACHb5CZAA)

That being said, I'm not entirely sure if this would actually be useful, since in most use cases the duration strings come from external APIs and so are not typechecked at compilation time. What do you think?

**Comment by WORMSS** [comment]
```ts
const valid: Duration = 'P1Y2M4DT20H44M12,67S';
```
this is a valid string, but shows as invalid in your typing.
![image](https://user-images.githubusercontent.com/1384537/163159580-82ac40fa-c6b0-42e9-b29f-141eb3397884.png)

**Comment by tolu** [comment]
seems like a lot of work to get that beast of a type to work as expected, PR's are very welcome though 😉

**Comment by WORMSS** [comment]
Not to mention, it doesn't allow `P1Y` to be a valid type either. Though that would be solved with another union without the T section.
