### ISSUE TITLE
Use of commas

### ISSUE THREAD

**Issue by WORMSS** [tolu/ISO8601-duration#25]
You have correctly allowed , as part of the number..
```js
const numbers = '\\d+(?:[\\.,]\\d+)?'
```
but sadly, you are then straight up using `parseFloat()` which treats `"0,5"` as `0`

You may need to do something such as 
```js
prev[objMap[idx]] = parseFloat(next ? next.replace(/,/g, '.') : next) || 0
```

Though, I will admit, not the best looking logic

**Comment by tolu** [comment]
Sorry for the late reply 🙏 

Thanks for the feedback, good catch!
Would have thought I should have added a test for that considering 😆 

Working on fix ✌️
