### ISSUE TITLE
Error while parsing fraction

### ISSUE THREAD

**Issue by RHOOPH** [tolu/ISO8601-duration#32]
The Doc says ```Fractions are allowed on the smallest unit in the string, e.g. P0.5D or PT1.0001S but not PT0.5M0.1S.```

However `parse("P0.5D")` causes error

![image](https://user-images.githubusercontent.com/16752005/222053457-05268c34-7651-4bc2-96b5-96e359dc6d73.png)

[Link to the example](https://codesandbox.io/s/suspicious-tesla-3eqwmc?file=/src/index.js)

Fractions in Years, Months and Weeks also causes the same error.

**Comment by tolu** [comment]
Thanks for the issue, are you willing to create a PR with a fix?

**Comment by tolu** [comment]
I agree that the wikipedia article implies that fractions can be used in Date values, however since Temporal throws a fit (`invalid duration`) for that I'll stick to their interpretation and close this issue 🙏 

```ts
try {
  Temporal.Duration.from("PT0.5Y").total({
    unit: "second",
    relativeTo: relativeDate.toISOString(),
  });
} catch (e) {
  // RangeError: invalid duration: PT0.5Y
  console.error(e);
}```
