### ISSUE TITLE
toSeconds may return incorrect values when daylight savings time changes

### ISSUE THREAD

**Issue by bumblebot1** [tolu/ISO8601-duration#35]
During the last time change on 5 November, while using the `toSeconds` method to parse durations, I noticed that it may return negative values when time changes from summer time to standard time even if the duration being parsed is supposed to be positive.

It looks like this happens because `new Date().getTime()` is called in two independent locations. If the time differs between the two calls (for example during Daylight Saving Time changes) it will return an incorrect value.

**Comment by tolu** [comment]
That should have been adressed by https://github.com/tolu/ISO8601-duration/pull/34 but if you find any other situations that are not accounted for please provide an example of feel free to add a PR 🙏

**Comment by tolu** [comment]
it should be easy to provide an example where this module produces a different result than the [@js-temporal/polyfill](https://www.npmjs.com/package/@js-temporal/polyfill) that I test against to ensure compliance. If so then there is absolutely a bug in this module.

**Comment by bumblebot1** [comment]
Thank you, it looks like that commit has solved the issue.

I was using this example to reproduce it in version 2.1.1 of the library (before that commit):
```
let start = new Date("2023-10-29T02:00:00.000+01:00")
result = module.toSeconds({minutes:5}, second)
// value of result would be -3300
```

With version 2.1.2 of the library (which includes that commit) the result returned is correct:
```
let start = new Date("2023-10-29T02:00:00.000+01:00")
result = module.toSeconds({minutes:5}, second)
// value of result would be 300
```
